"""
engine.py — CachePilot simulation engine with concurrent session management.

Real serving systems have many sessions active simultaneously, all fighting
for VRAM.  This engine maintains up to `max_concurrent` live sessions and
interleaves their decode steps round-robin.  Memory pressure is real because
sessions accumulate KV cache across their lifetimes while new sessions
continuously arrive.

This is the model that makes PERC's advantage over LRU visible: when VRAM
fills under concurrent load, which cached session gets evicted matters.
"""

from __future__ import annotations

import heapq
import random
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np

from .batcher import BatchMode, DynamicBatcher
from .eviction import LRUEviction, PERCEviction, PriorityEviction, EvictionPolicy
from .kv_manager import KVCacheManager
from .memory import VRAMPool
from .scheduler import Priority, RequestQueue, ScheduledRequest
from .simulator import SimRequest, load_generator
from .telemetry import TelemetryCollector

POLICY_MAP: Dict[str, EvictionPolicy] = {
    "perc": PERCEviction(),
    "lru": LRUEviction(),
    "priority": PriorityEviction(),
}

WORKLOAD_PRESETS: Dict[str, Dict[str, float]] = {
    "chat": {"chat": 1.0},
    "code": {"code": 1.0},
    "summarize": {"summarize": 1.0},
    "longctx": {"longctx": 1.0},
    "mixed": {"chat": 0.4, "code": 0.3, "summarize": 0.2, "longctx": 0.1},
}


@dataclass
class _ActiveSession:
    """A session currently live in the concurrent pool."""
    req: SimRequest
    tokens_done: int = 0
    tpot_list: List[float] = field(default_factory=list)


@dataclass
class RunResult:
    policy: str
    workload: str
    requests_served: int
    requests_dropped: int
    tokens_total: int
    throughput_tok_s: float
    p50_tpot_ms: float
    p95_tpot_ms: float
    p99_tpot_ms: float
    eviction_events: int
    # Total expected recompute cost across all evictions (seconds).
    # This is the quantity PERC directly minimizes.  Lower is strictly better.
    total_eviction_cost_s: float
    # Mean cost per eviction event — normalizes for differences in event count.
    mean_eviction_cost_s: float
    vram_util_mean: float
    vram_util_peak: float
    wall_time_s: float

    def as_dict(self) -> Dict:
        return dict(self.__dict__)


def run(
    policy: str = "perc",
    workload: str = "mixed",
    n_requests: int = 1000,
    arrival_rate: float = 10.0,
    vram_gb: float = 24.0,
    pinned_fraction: float = 0.35,
    seed: int = 42,
    spike_at: Optional[int] = None,
    spike_multiplier: float = 4.0,
    batch_mode: str = "adaptive",
    max_concurrent: int = 32,
) -> RunResult:
    """
    Simulate a serving system with up to max_concurrent live sessions.

    Sessions are generated by the load generator and admitted as VRAM allows.
    Each simulation tick advances all active sessions by one decode step,
    then tries to admit new requests.  When VRAM is tight, the eviction policy
    decides which cached session to sacrifice to make room for a new admission.

    max_concurrent controls how many sessions run in parallel — higher values
    create more memory pressure and make PERC's cost-aware eviction matter more.
    """
    eviction_policy = POLICY_MAP.get(policy, PERCEviction())
    mix = WORKLOAD_PRESETS.get(workload, WORKLOAD_PRESETS["mixed"])

    pool = VRAMPool(total_gb=vram_gb, pinned_gb=vram_gb * pinned_fraction)
    kv = KVCacheManager(pool, policy=eviction_policy)
    telemetry = TelemetryCollector()
    rng = random.Random(seed + 1)

    all_requests = list(
        load_generator(mix, n_requests, arrival_rate, seed, spike_at, spike_multiplier)
    )

    # Track per-request results
    tpot_all: List[float] = []
    vram_utils: List[float] = []
    served = 0
    dropped = 0
    tokens_total = 0

    # Simulate wall time using the arrival timestamps in the load generator
    sim_time = 0.0
    request_queue: List[SimRequest] = list(all_requests)  # ordered by arrival
    next_idx = 0
    active: List[_ActiveSession] = []

    import time as _time
    wall_start = _time.monotonic()

    while next_idx < len(request_queue) or active:
        # ------------------------------------------------------------------
        # Admit new sessions up to max_concurrent (or as VRAM allows)
        # ------------------------------------------------------------------
        while len(active) < max_concurrent and next_idx < len(request_queue):
            req = request_queue[next_idx]
            admitted = kv.register_session(req.req_id, req.prompt_len)
            if admitted:
                active.append(_ActiveSession(req=req))
                next_idx += 1
            else:
                # VRAM exhausted even after eviction attempt — drop request
                dropped += 1
                next_idx += 1

        if not active:
            break

        # ------------------------------------------------------------------
        # Advance all active sessions by one decode step
        # ------------------------------------------------------------------
        completed: List[int] = []
        for i, sess in enumerate(active):
            if sess.req.done:
                completed.append(i)
                continue
            tokens, latency_s = sess.req.step(batch_size=1, rng=rng)
            ok = kv.extend_session(sess.req.req_id, tokens)
            if not ok:
                # OOM even mid-session — terminate and count as served
                completed.append(i)
            else:
                tpot_ms = latency_s * 1000.0 / max(tokens, 1)
                sess.tpot_list.append(tpot_ms)
                sess.tokens_done += tokens
                telemetry.record_tokens(sess.req.req_id, tokens, tpot_ms)

        # ------------------------------------------------------------------
        # Retire completed sessions
        # ------------------------------------------------------------------
        for i in sorted(completed, reverse=True):
            sess = active.pop(i)
            kv.release_session(sess.req.req_id)
            if sess.tpot_list:
                tpot_all.extend(sess.tpot_list)
                tokens_total += sess.tokens_done
                served += 1

        # Telemetry snapshot every N ticks
        if served % 20 == 0:
            stats = pool.stats()
            vram_utils.append(stats.utilization)
            telemetry.snapshot(stats.utilization, 0, kv.active_sessions)

    wall = _time.monotonic() - wall_start
    tpot_arr = np.array(tpot_all) if tpot_all else np.array([0.0])

    eviction_log = kv.eviction_log
    total_eviction_cost = sum(e.expected_recompute_cost_s for e in eviction_log)
    n_evictions = len(eviction_log)

    return RunResult(
        policy=policy,
        workload=workload,
        requests_served=served,
        requests_dropped=dropped,
        tokens_total=tokens_total,
        throughput_tok_s=tokens_total / max(wall, 1e-3),
        p50_tpot_ms=float(np.percentile(tpot_arr, 50)),
        p95_tpot_ms=float(np.percentile(tpot_arr, 95)),
        p99_tpot_ms=float(np.percentile(tpot_arr, 99)),
        eviction_events=n_evictions,
        total_eviction_cost_s=total_eviction_cost,
        mean_eviction_cost_s=total_eviction_cost / max(n_evictions, 1),
        vram_util_mean=float(np.mean(vram_utils)) if vram_utils else 0.0,
        vram_util_peak=float(np.max(vram_utils)) if vram_utils else 0.0,
        wall_time_s=wall,
    )
